FROM postgres:15

# 시스템 패키지 설치
RUN apt-get update && apt-get install -y \
    postgresql-15-postgis-3 \
    postgresql-15-postgis-3-scripts \
    postgresql-15-pgrouting \
    postgresql-15-pgrouting-scripts \
    postgresql-contrib-15 \
    && rm -rf /var/lib/apt/lists/*

# 초기화 스크립트 생성
COPY ./init-extensions.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init-extensions.sh 