version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: foodpick-postgres
    ports:
      - '5000:5432'
    environment:
      POSTGRES_USER: foodpick
      POSTGRES_PASSWORD: foodpick123
      POSTGRES_DB: foodpick
      JAVA_OPTS: '-Xmx4096m'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - foodpick-network
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 1G
    shm_size: 1G
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: foodpick-api
    ports:
      - '2100:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://foodpick:foodpick123@postgres:5432/foodpick
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - foodpick-network
    restart: on-failure

volumes:
  postgres_data:

networks:
  foodpick-network:
    external: true
